url: http://gjermundbjaanes.com
name: Gjermund Bjaanes
title: Gjermund Bjaanes
email: bjaanes@gmail.com
description: Programming, Productivity and Lifestyle
github_username: bjaanes
twitter_username: gjermundbjaanes